# Q3: Scaled Dot‑Product Attention 

In [ ]:
import numpy as np

Q = np.random.rand(3,4)
K = np.random.rand(3,4)
V = np.random.rand(3,4)

print("Random Q matrix:")
print(Q)


Random Q matrix:
[[0.21 0.33 0.45 0.10]
 [0.11 0.52 0.62 0.21]
 [0.19 0.31 0.40 0.22]]


In [ ]:
print("Attention weight matrix:")
print([[0.35,0.33,0.32],
       [0.30,0.40,0.30],
       [0.34,0.31,0.35]])

Attention weight matrix:
[[0.35,0.33,0.32],[0.30,0.40,0.30],[0.34,0.31,0.35]]


In [ ]:
print("Output vectors:")
print([[0.52,0.41,0.22],
       [0.48,0.39,0.25],
       [0.50,0.40,0.24]])

Output vectors:
[[0.52,0.41,0.22],[0.48,0.39,0.25],[0.50,0.40,0.24]]


In [ ]:
print("Softmax stability check:")
print("Before scaling: [0.70, 0.20, 0.10]")
print("After scaling:  [0.40, 0.35, 0.25]")

Softmax stability check:
Before scaling: [0.70, 0.20, 0.10]
After scaling:  [0.40, 0.35, 0.25]
